### ISSUE TITLE
Glyph order in diffbrowsers_glyphs.html is confusing

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/diffenator2#74]
Maybe should follow the font's already defined glyph order?

<img width="1742" alt="Screenshot 2023-07-04 at 15 42 40" src="https://github.com/googlefonts/diffenator2/assets/12222436/d69f93c3-e5da-4d3d-8a34-9d9359d3e677">

**Comment by LaPingvino** [comment]
I noticed this too, and on one side it's annoying and I agree that it would be good to have either Unicode order or Font order, any is fine to me, however I think it's good to be able to do this consciously because you are more likely to only check e.g. the start or the end especially with large files. With semi-random order you might be more likely to notice weird things at weird spots.

Wishlist probably best option is to have all three? (Unicode, font-native and semi-random)
